# Generated by Django 3.1.7 on 2021-11-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210911_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
        migrations.AddField(
            model_name='profile',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
