# Generated by Django 3.1.7 on 2021-12-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211123_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='osa_token',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
