# Generated by Django 3.1.7 on 2021-12-26 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211212_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='osa_token',
        ),
    ]
