# Generated by Django 3.1.7 on 2022-01-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_osa_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='accounts/default.png', upload_to='accounts/'),
        ),
    ]
