# Generated by Django 3.1.7 on 2022-01-14 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='picture',
            new_name='image',
        ),
    ]
