export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED = "LOGOUT_FAILED";

export const BOOKS_FETCH_REQUEST = "BOOKS_FETCH_REQUEST";
export const BOOKS_FETCH_SUCCESS = "BOOKS_FETCH_SUCCESS";
export const BOOKS_FETCH_FAILED = "BOOKS_FETCH_FAILED";

export const BOOK_CREATE_REQUEST = "BOOK_CREATE_REQUEST";
export const BOOK_CREATE_SUCCESS = "BOOK_CREATE_SUCCESS";
export const BOOK_CREATE_FAILED = "BOOK_CREATE_FAILED";

export const GROUPS_FETCH_REQUEST = "GROUPS_FETCH_REQUEST";
export const GROUPS_FETCH_SUCCESS = "GROUPS_FETCH_SUCCESS";
export const GROUPS_FETCH_FAILED = "GROUPS_FETCH_FAILED";

export const ELECTRONICS_FETCH_REQUEST = "ELECTRONICS_FETCH_REQUEST";
export const ELECTRONICS_FETCH_SUCCESS = "ELECTRONICS_FETCH_SUCCESS";
export const ELECTRONICS_FETCH_FAILED = "ELECTRONICS_FETCH_FAILED";

export const OTHER_FETCH_REQUEST = "OTHER_FETCH_REQUEST";
export const OTHER_FETCH_SUCCESS = "OTHER_FETCH_SUCCESS";
export const OTHER_FETCH_FAILED = "OTHER_FETCH_FAILED";
