# Generated by Django 3.1.7 on 2021-06-18 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-vote_count_log__upvote_count', '-created_at']},
        ),
    ]
