# Generated by Django 3.1.7 on 2021-06-18 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteCountLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VoteLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('saved_flag', models.BooleanField(default=False)),
                ('upvoted_flag', models.BooleanField(default=False)),
                ('dismiss_flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='vote',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='post',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='voted_by',
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(default='active', max_length=100),
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
        migrations.AddField(
            model_name='votelog',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_log', to='posts.post'),
        ),
        migrations.AddField(
            model_name='votelog',
            name='voted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_log', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='votecountlog',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vote_count_log', to='posts.post'),
        ),
    ]
