# Generated by Django 3.1.7 on 2021-08-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210618_2046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.AlterField(
            model_name='skilllist',
            name='type',
            field=models.CharField(choices=[('TECH', 'Technical')], default='TECH', max_length=4),
        ),
        migrations.DeleteModel(
            name='SkillType',
        ),
    ]
