# Generated by Django 3.1.7 on 2021-04-05 11:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_auto_20210317_2002'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('voted_by', 'post', 'choice')},
        ),
    ]
