# Generated by Django 3.1.7 on 2021-04-12 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_skill_skilllist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='skill',
            new_name='skill_item',
        ),
    ]
