# Generated by Django 3.1.7 on 2021-12-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20211103_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilllist',
            name='frequency',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
