# Generated by Django 3.1.7 on 2021-12-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_remove_skilllist_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilllist',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
