# Generated by Django 3.1.7 on 2021-12-13 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20211213_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skilllist',
            options={'ordering': ['-frequency']},
        ),
    ]
