# Generated by Django 3.1.7 on 2021-12-13 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20211213_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='name',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='skilllist',
            old_name='name',
            new_name='label',
        ),
    ]
