# Generated by Django 3.1.7 on 2022-01-31 14:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 31, 14, 19, 34, 53786, tzinfo=utc)),
        ),
    ]
