# Generated by Django 3.1.7 on 2022-02-01 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='text',
        ),
    ]
