# Generated by Django 3.1.7 on 2022-02-01 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_auto_20211226_2123'),
        ('posts', '0022_remove_notification_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.conversation')),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.notification')),
            ],
        ),
    ]
