# Generated by Django 3.1.7 on 2022-02-01 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_messagenotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageNotification',
        ),
    ]
