# Generated by Django 3.1.7 on 2022-02-01 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_auto_20211226_2123'),
        ('posts', '0024_delete_messagenotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.message')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_notification', to='posts.notification')),
            ],
        ),
    ]
