# Generated by Django 3.1.7 on 2022-02-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_auto_20220201_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('MSG', 'message'), ('TAG', 'mention'), ('VOTE', 'upvote'), ('FLW', 'follow')], max_length=5),
        ),
    ]
