# Generated by Django 3.1.7 on 2022-02-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_auto_20220203_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members_needed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
