# Generated by Django 3.1.7 on 2022-04-08 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_auto_20220219_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_expired',
            new_name='is_archived',
        ),
    ]
