# Generated by Django 3.1.7 on 2021-12-26 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_auto_20211226_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp', 'pk']},
        ),
    ]
